Fix schema loading when no default profile
aws/aws-sam-cli pull request #2441
Opened 2020-12-03 01:45 UTC by kylelaker

The region_name value when a profile does not specify a region or when
there is not a 'default' profile resulted in a crash since
_get_aws_region_choice attempted to perform concatenation using the `+`
operator (which is undefined for str + NoneType). Using an actual string
formatting method fixes that issue.

Additionally, it is useless to prompt the user whether not to use the
'default' profile since doing so is impossible. They need to be
prompted. Additionally, it is slightly more 'intelligent' to create a
new session after the user has chosen a new profile so that a better
default region can be chosen.

#### Which issue(s) does this change fix?

No issue was opened.

#### Why is this change necessary?
The `sam init` crashes if a user needs to pick a schema and they do not have a `default` profile or their `default` profile does not specify a `region`. (`TypeError` in `_get_aws_region_choice`)

#### How does it address the issue?
Avoids performing a `+` operation to perform string concatenation.

#### What side effects does this change have?
Does not prompt the user to accept the defaults if doing so results in `region` being None. Just moves on to asking the user. 

#### Checklist

- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ X ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2020-12-31 09:39 UTC, moelasmar requested changes
Can you add unit/integration test cases that cover this change

2020-12-31 22:19 UTC, kylelaker commented
@moelasmar: Unit test coverage for the new code path(s) has been added

2021-03-16 19:38 UTC, CoshUS approved these changes

2021-03-25 22:24 UTC, moelasmar approved these changes

2021-03-27 10:10 UTC, merged