fix: Catch more errors when building an image
aws/aws-sam-cli pull request #2857
Opened 2021-05-05 21:40 UTC by valerena

In certain scenarios, the error from the Docker build is not
raised as an exception, but it's returned as part of the command's
output.

#### Which issue(s) does this change fix?

#### Why is this change necessary?
In the current situation, when invoking a function locally, if for some reason building the rapid image fails, then the error shown to the user is raised later in the process, hiding the actual build error.

#### How does it address the issue?
The response of the build command is now taken into account, checking if there's an error, and throwing a Build Exception when that's the case.

#### What side effects does this change have?
N/A

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [x] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2021-05-06 00:12 UTC, sriram-mv approved these changes

2021-05-06 00:18 UTC, sriram-mv requested changes

2021-05-06 00:18 UTC, sriram-mv commented on tests/unit/local/docker/test_lambda_image.py
> +    def test_build_image_fails_with_BuildError_from_output(
could we add an integration test oo?

2021-05-21 21:05 UTC, valerena commented on samcli/lib/build/build_graph.py
> +            f"{self.build_method}, {self.compatible_runtimes}, {self.env_vars})"
This change comes from this commit, that's already merged into `aws:develop`: https://github.com/aws/aws-sam-cli/commit/199ded1901964ed17023e9d5ed5682ff77ae3dfd I'm not sure why it appears here

2021-05-26 17:28 UTC, sriram-mv approved these changes

2021-05-26 18:02 UTC, mgrandis approved these changes

2021-06-10 20:39 UTC, merged