Updating tomlkit version as we need fix of the dataloss bug during copy() method use on Table object
aws/aws-sam-cli pull request #2939
Opened 2021-06-07 18:58 UTC by c2tarun

#### Which issue(s) does this change fix?

#2923 

#### Why is this change necessary?
We use copy() method when trying to parse tomlconfig. The updated version has a fix which prevents values during copy operation.

#### How does it address the issue?

#### What side effects does this change have?

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2021-06-07 22:21 UTC, aahung approved these changes

2021-06-09 13:02 UTC, jfuss requested changes
The changes seem reasonable. Should we have some additional integ tests so we can make sure this behavior isn't regressed in the future?

2021-06-09 13:02 UTC, jfuss commented on requirements/reproducible-linux.txt
> +tomlkit==0.7.2 \
We need to make sure we update our THIRD-PARTY-LICENSES file: https://github.com/aws/aws-sam-cli/blob/develop/installer/assets/THIRD-PARTY-LICENSES#L2490

2021-06-09 15:00 UTC, c2tarun commented
> The changes seem reasonable. Should we have some additional integ tests so we can make sure this behavior isn't regressed in the future?

Sure, added integ test.

> We need to make sure we update our THIRD-PARTY-LICENSES file: https://github.com/aws/aws-sam-cli/blob/develop/installer/assets/THIRD-PARTY-LICENSES#L2490

I think this file wasn't updated in some time. Updating it now, several updates in this file.

2021-06-09 15:51 UTC, jfuss commented
We recently updated the THRID-PARTY-LICENSES in https://github.com/aws/aws-sam-cli/pull/2929/files. Looks like you might not have had an updated version of `develop` given the conflicts.

2021-06-09 16:03 UTC, jfuss approved these changes

2021-06-09 16:24 UTC, sriram-mv approved these changes

2021-06-09 16:24 UTC, merged