fix: pass copy of environment variables for keeping cache valid
aws/aws-sam-cli pull request #2943
Opened 2021-06-10 18:34 UTC by mndeveci

#### Which issue(s) does this change fix?
https://github.com/aws/aws-sam-cli/issues/2885

#### Why is this change necessary?
When building inside the container, we add additional environment variables like `LAMBDA_BUILDERS_LOG_LEVEL` which is causing cache to be invalid all the time. 

#### How does it address the issue?
We are sending a copy of the dictionary instead of reference to original one, so additional changes won't affect function build definition and cache information.

#### What side effects does this change have?
N/A

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [x] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2021-06-10 18:38 UTC, jfuss requested changes
Integ tests to strengthen our testing suite against future regressions?

2021-06-10 18:52 UTC, mndeveci commented
> Integ tests to strengthen our testing suite against future regressions?

@jfuss good point, added integ tests 👍🏼

2021-06-24 20:42 UTC, jfuss approved these changes

2021-06-28 18:01 UTC, qingchm approved these changes
LGTM

2021-06-29 01:50 UTC, merged