fix: Skip image-repository validation of ECR images (#2934)
aws/aws-sam-cli pull request #3015
Opened 2021-07-02 07:58 UTC by alexisfacques

#### Which issue(s) does this change fix?

Issue #2934

#### Why is this change necessary?

- Fix/Resolve the `image_repository_validation` for Docker-packaged lambda functions with valid ECR locations (Issue #2934, introduced in PR #2935);
- Remove Docker-packaged lambda functions with valid ECR locations from the `--guided` guided context prompts.
- Check for `DockerContext` resource metadata prior to skipping the image build.

#### How does it address the issue?

- Instead of resolving packageable Image functions from the raw template file(s) (`get_template_function_resource_ids`, `get_template_artifacts_format`), use the `SamFunctionProvider` to do so (evaluating template parameters values, so the template must go through the IntrinsicResolver).

#### What side effects does this change have?

- `get_template_function_resource_ids`, `get_template_artifacts_format` are obsolete (not yet deleted from the repo);

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2022-06-17 21:09 UTC, qingchm commented
In order for this to be properly reviewed please resolve the merge conflicts and make sure that make pr passes!

2022-06-17 21:11 UTC, qingchm requested changes
Unfortunately this does not meet the PR requirements yet, please make sure the listed requirements are met.

2022-06-21 07:08 UTC, alexisfacques commented
Heya guys! Ooops, forgot this was still WIP. 
Will rebase on the current release asap

2022-07-05 12:47 UTC, mndeveci commented
@alexisfacques I am marking this PR as draft for now. Please mark it ready once you addressed previous comments.

2022-08-09 20:38 UTC, jfuss commented
Closing as inactive.

Happy to review an updated PR from the community, if someone wants to revive the PR

2022-08-09 20:38 UTC, closed without merging