New release of RIE: 1.1
aws/aws-sam-cli pull request #3029
Opened 2021-07-08 18:07 UTC by valerena

#### Which issue(s) does this change fix?

#### Why is this change necessary?
Consume the latest version of [RIE](https://github.com/aws/aws-lambda-runtime-interface-emulator/)

#### How does it address the issue?
It bring the latest version of RIE

#### What side effects does this change have?

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2021-07-08 18:37 UTC, jfuss submitted a review, later dismissed

2021-07-08 18:40 UTC, mgrandis approved these changes

2021-08-24 21:04 UTC, sriram-mv approved these changes

2021-08-25 13:44 UTC, jfuss requested changes
No specific requests but we have seen problems with the new rie when trying this locally. We don't yet understand why. Requesting changes to mark this as "do not merge".

2021-08-30 21:43 UTC, wchengru commented
The binary is updated in this PR: https://github.com/aws/aws-sam-cli/pull/3216
The RIE PR to fix this is: https://github.com/aws/aws-lambda-runtime-interface-emulator/pull/45

2021-08-31 15:58 UTC, jfuss commented
Closing in favor of #3216

2021-08-31 15:58 UTC, closed without merging