fix: Add all files under samcli module
aws/aws-sam-cli pull request #3177
Opened 2021-08-17 17:58 UTC by jfuss

When we released the `sam pipeline` set of commands, we didn't update
the MANIFEST.in file. This file controls what files get added or ignored
when the .whl file is created. When we add non python files, we need to
remember to update the MaNIFEST.in file. This commit will auto include
any files within the samcli module but exlcude .pyc files. This might
create a bigger .whl but will make sure the cli works going forward.

I did some quick tests and compared 1.28 .whl to one I produced with this
commit. I did not see any differences in the diff.

#### Which issue(s) does this change fix?

#### Why is this change necessary?

#### How does it address the issue?

#### What side effects does this change have?

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2021-08-17 18:07 UTC, CoshUS approved these changes

2021-08-17 18:42 UTC, wchengru approved these changes

2021-08-17 19:51 UTC, jfuss commented
I haven't been able to replicate the failing unit test locally. Something is non-deterministic about `tests/unit/lib/telemetry/test_metric.py::TestTrackCommand::test_must_record_function_duration`

2021-08-18 16:05 UTC, CoshUS requested changes

2021-08-18 16:05 UTC, CoshUS commented on tests/unit/lib/telemetry/test_metric.py
> +            "Measured duration must be in milliseconds and greater than equal to  the sleep duration",
Does the duration change break what this test is intended to check? The error message suggests this test is asserting that functions run less than 1 second should be recorded.

2021-08-18 16:51 UTC, jfuss commented on tests/unit/lib/telemetry/test_metric.py
> +            "Measured duration must be in milliseconds and greater than equal to  the sleep duration",
I don't think so. My reasoning is that the test name is `test_must_record_function_duration`, which suggests it's scope it recording the duration. The comment is giving the explanation of why is failed, I don't think the duration actually matters for this test (other than asserting our duration is greater than the sleep_duration).

2021-08-18 17:03 UTC, CoshUS approved these changes

2021-08-20 01:21 UTC, merged