updates the local API service to include CORS headers
aws/aws-sam-cli pull request #3357
Opened 2021-10-12 19:04 UTC by jlapier

Previous to this commit, `sam local api` would only return CORS headers when an OPTIONS request is made. This causes issues for browsers, which expect at the very least "Access-Control-Allow-Origin" to be present on other HTTP methods. This commit adds the "Access-Control-Allow-Origin" header to a request if it is made with one of the Allowed-Methods.

References:
 * Fetch spec on CORS: https://fetch.spec.whatwg.org/#cors-request
 * Examples from Mozilla: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
 * API Gateway doc on when to supply CORS headers: https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html

#### Which issue(s) does this change fix?

#1460 

#### Why is this change necessary?

In order to test a local UI against a local API via sam, proper CORS headers are required or the browser will reject the requests.

#### How does it address the issue?

Adds the Access-Control-Allow-Origin header if a CORS configuration is present for the API.

#### What side effects does this change have?

The CORS header behavior is not entirely predictable for REST APIs, according to the [AWS API Gateway docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html). This change may mask a need to include the headers at the integration point. However, for [HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-cors.html), the behavior is much more predicable and this change is consistent with that behavior.

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [x] Write/update integration tests
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2022-03-18 19:11 UTC, vmarinescu approved these changes

2022-08-11 16:59 UTC, jfuss requested changes

2022-08-11 16:59 UTC, jfuss commented on samcli/local/apigw/local_apigw_service.py
> +            response_headers.add_header("Access-Control-Allow-Origin", allow_origin)
According to the API Gateway docs, the Lambda function is responsible for adding these integrations: https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html (in the "Enabling CORS support for Lambda or HTTP proxy integrations" section). So SAM CLI should not be doing this.

2022-08-11 16:59 UTC, jfuss commented on samcli/local/apigw/local_apigw_service.py
> +                response_headers.add_header("Vary", "Origin")
Does API Gateway add this?

2022-08-11 16:59 UTC, jfuss commented on samcli/local/apigw/local_apigw_service.py
> +        query_string_dict = LocalApigwService._query_string_params_v_2_0(flask_request)
I don't understand how this relates to the CORS headers.

2022-08-16 15:01 UTC, jfuss commented
Closing given no response. Feel free to address comments and re-open and we will re-review.

2022-08-16 15:01 UTC, closed without merging