feat: command to add additional host
aws/aws-sam-cli pull request #3551
Opened 2021-12-28 03:18 UTC by darthzyklus

#### Which issue(s) does this change fix?

#### Why is this change necessary?
Because on Linux environment is not enable by default the host.docker.internal hostname which it is use to connect to local services and doing this via docker-compose seems an overkill.  Window and Mac users use host.docker.internal so easy, I think this will be good for the Linux users too

#### How does it address the issue?
Add one more command to the container command

#### What side effects does this change have?
Make host.docker.internal usable to connect with localhost services 

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [x] Write unit tests
- [x] Write/update functional tests
- [x] Write/update integration tests
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2021-12-28 03:34 UTC, darthzyklus commented
the following check seems that is not related  https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli/builds/42019851

2021-12-30 21:00 UTC, hoffa requested changes
Thanks for the PR! 🙏 Added a few comments.

2021-12-30 21:01 UTC, hoffa commented
> the following check seems that is not related https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli/builds/42019851

From the logs:

```text
************* Module samcli.local.lambdafn.runtime
samcli/local/lambdafn/runtime.py:48:0: C0301: Line too long (135/120) (line-too-long)
samcli/local/lambdafn/runtime.py:100:0: C0301: Line too long (138/120) (line-too-long)
samcli/local/lambdafn/runtime.py:128:0: C0301: Line too long (129/120) (line-too-long)
samcli/local/lambdafn/runtime.py:184:0: C0301: Line too long (129/120) (line-too-long)
samcli/local/lambdafn/runtime.py:350:0: C0301: Line too long (135/120) (line-too-long)
samcli/local/lambdafn/runtime.py:391:0: C0301: Line too long (128/120) (line-too-long)
************* Module samcli.commands.local.cli_common.invoke_context
samcli/commands/local/cli_common/invoke_context.py:264:0: C0301: Line too long (138/120) (line-too-long)
```

Running `make format` should fix that.

2022-01-17 01:06 UTC, darthzyklus commented
Thanks @hoffa I will check it.

2022-01-17 01:07 UTC, darthzyklus commented on samcli/commands/local/cli_common/options.py
> +            default="host.docker.internal",
Sure I get it

2022-01-17 01:08 UTC, darthzyklus commented on samcli/commands/local/cli_common/options.py
> +            "--container-add-host",
I will add it, thanks

2022-01-26 20:38 UTC, qingchm commented
Hi @darthzyklus I'll try to help with a review, can we try to do a merge from the latest develop changes and resolve the following conflicts please?
```
samcli/local/docker/lambda_container.py
samcli/local/lambdafn/runtime.py
tests/unit/local/lambdafn/test_runtime.py 
```
Thanks!

2022-02-16 23:02 UTC, darthzyklus commented
Hi @qingchm sry for the delay. I will resolve the conflicts this week. Maybe I need a little help with some python concepts because I am little lost

2022-03-31 20:25 UTC, hawflau commented
Hey @darthzyklus, have you been able to address the change requests and resolve the conflicts?

2022-04-03 05:31 UTC, darthzyklus commented
hi  @hawflau . Yes, I took it a look  to the conflicts and changes requested

I will try to make the changes now I will have more free time these upcoming days.

2022-04-20 20:51 UTC, moelasmar commented
Thanks @darthzyklus for your contribution. I will mark this PR as draft till you can finalize the requested changes, and resolve the conflicts. Please change it to ready once you finish.

2022-08-09 20:46 UTC, jfuss commented
Closing as inactive.

Happy to review an updated PR from the community, if someone wants to revive the PR

2022-08-09 20:46 UTC, closed without merging