Fix: Make resource syncs respect base dir option
aws/aws-sam-cli pull request #3579
Opened 2022-01-12 23:40 UTC by qingchm

#### Which issue(s) does this change fix?

#### Why is this change necessary?

#### How does it address the issue?

#### What side effects does this change have?

#### Checklist

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write unit tests
- [ ] Write/update functional tests
- [ ] Write/update integration tests
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2022-01-13 19:47 UTC, CoshUS requested changes
nit: Can we add description in the PR for future tracking?
Rest looks good to me. Thanks for addressing this!

2022-01-14 05:58 UTC, super132 commented
> #### Which issue(s) does this change fix?
> #### Why is this change necessary?
> #### How does it address the issue?
> #### What side effects does this change have?
> #### Checklist
> * [ ]  Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
> * [ ]  Write design document ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
> * [x]  Write unit tests
> * [ ]  Write/update functional tests
> * [ ]  Write/update integration tests
> * [x]  `make pr` passes
> * [ ]  `make update-reproducible-reqs` if dependencies were changed
> * [ ]  Write documentation
> 
> By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

Can you please link the issue that this PR addresses and a description of why do we need this change and what is the change about?

Thanks.

2022-01-17 23:23 UTC, CoshUS commented on tests/unit/lib/sync/flows/test_rest_api_sync_flow.py
> +        self.assertEqual(result_uri, "base_dir/test_uri")
"/" is for unix. On Windows "\" must be used instead.
Use "os.path.sep" instead.

2022-01-18 07:35 UTC, mndeveci approved these changes
Thanks for working on this, it looks good other than the feedback that @CoshUS gave.

2022-01-18 07:35 UTC, mndeveci commented on tests/unit/lib/sync/flows/test_stepfunctions_sync_flow.py
> +        self.assertEqual(result_uri, "base_dir/test_uri")
Please replace this forward slash as well.

2022-01-20 01:23 UTC, CoshUS approved these changes

2022-01-20 13:49 UTC, merged