SAM INIT Revamp
aws/aws-sam-cli pull request #3601
Opened 2022-01-25 19:59 UTC by jonife

2022-01-25 20:09 UTC, mndeveci commented on samcli/commands/init/init_templates.py
> +        self.manifest_url = "https://raw.githubusercontent.com/aws/aws-sam-cli-app-templates/master/manifest.json"
Let's put it in a static variable just like `APP_TEMPLATES_REPO_URL`.

2022-01-25 20:09 UTC, mndeveci commented on samcli/commands/init/init_templates.py
> +            self.clone_templates_repo()
adding a log line could be helpful here to state that getting manifest file directly have failed and we are falling back to cloning the repository.

2022-01-27 02:21 UTC, mndeveci requested changes

2022-01-27 02:21 UTC, mndeveci commented on samcli/commands/init/init_templates.py
> +            LOG.debug("Clone error, attempting to use an old clone from a previous run")
I think one of these log messages are redundant?

2022-01-27 02:21 UTC, mndeveci commented on samcli/commands/init/interactive_init_flow.py
>          if click.confirm("\n Use the most popular runtime and package type? (Nodejs and zip)"):
We forgot to update messaging here, should we use variables here instead of writing them static?

2022-02-01 22:07 UTC, mndeveci approved these changes

2022-02-16 00:16 UTC, moelasmar approved these changes

2022-02-16 23:13 UTC, merged