fix: Update Python3.6 Debug Bootstrap Path
aws/aws-sam-cli pull request #3708
Opened 2022-03-03 18:17 UTC by CoshUS

#### Which issue(s) does this change fix?

N/A

#### Why is this change necessary?
Python3.6 emulation images now uses `/var/runtime/bootstrap.py` instead of `/var/runtime/awslambda/bootstrap.py`.
Although `/var/runtime/awslambda/bootstrap.py` is still a symlink to the new path, we want to update the path for the future.

#### How does it address the issue?
Changes the path to `/var/runtime/bootstrap.py`.

#### What side effects does this change have?
None

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [x] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [x] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [x] Write/update unit tests
- [x] Write/update integration tests
- [x] Write/update functional tests if needed
- [ ] `make pr` passes
- [x] `make update-reproducible-reqs` if dependencies were changed
- [x] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2022-03-03 20:59 UTC, jfuss requested changes
Debugging doesn't have test associated with it (we could never figure out how to run automated tests). Given that, how did we validate this works as expected?

I only "request changes" to understand the above, the code looks fine to me.

2022-03-03 22:56 UTC, CoshUS commented
Tested locally by running `samdev local invoke -d` with the new image.

Setting path to invalid path, `/var/runtime/awslambda/bootstrap2.py`, in order to get a failure case. Validating changes are reflected.
```
(.env) PS E:\Dev\Amazon\Workspace\sam-apps\python3.6> samdev local invoke -d 5555
Invoking app.lambda_handler (python3.6)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-python3.6:rapid-1.40.1-x86_64.

Mounting E:\Dev\Amazon\Workspace\sam-apps\python3.6\.aws-sam\build\HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 640dd8b5-3e6f-4be6-b3ab-17bb607f38a3 Version: $LATEST
/var/lang/bin/python3.6: can't open file '/var/runtime/awslambda/bootstrap2.py': [Errno 2] No such file or directory
03 Mar 2022 18:13:43,715 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 2 InvokeID=
/var/lang/bin/python3.6: can't open file '/var/runtime/awslambda/bootstrap2.py': [Errno 2] No such file or directory
END RequestId: 590d478e-04b5-4895-af05-774b8e2f7cf6
REPORT RequestId: 590d478e-04b5-4895-af05-774b8e2f7cf6  Init Duration: 0.09 ms  Duration: 26.69 ms      Billed Duration: 27 ms  Memory Size: 128 MB     Max Memory Used: 128 MB
```

Setting path back to `/var/runtime/awslambda/bootstrap.py`
```
(.env) PS E:\Dev\Amazon\Workspace\sam-apps\python3.6> samdev local invoke -d 5555
Invoking app.lambda_handler (python3.6)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-python3.6:rapid-1.40.1-x86_64.

Mounting E:\Dev\Amazon\Workspace\sam-apps\python3.6\.aws-sam\build\HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 1615b7a9-8294-4f99-a66f-977305d76958 Version: $LATEST
END RequestId: 1615b7a9-8294-4f99-a66f-977305d76958
REPORT RequestId: 1615b7a9-8294-4f99-a66f-977305d76958  Init Duration: 0.09 ms  Duration: 102.01 ms     Billed Duration: 103 ms Memory Size: 128 MB     Max Memory Used: 128 MB
{"statusCode": 200, "body": "{\"message\": \"hello world\"}"}
```

Setting path to `/var/runtime/bootstrap.py`
```
(.env) PS E:\Dev\Amazon\Workspace\sam-apps\python3.6> samdev local invoke -d 5555
Invoking app.lambda_handler (python3.6)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-python3.6:rapid-1.40.1-x86_64.

Mounting E:\Dev\Amazon\Workspace\sam-apps\python3.6\.aws-sam\build\HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: f082a4ec-4bab-4463-b8c1-8fc2e77c7ce3 Version: $LATEST
END RequestId: f082a4ec-4bab-4463-b8c1-8fc2e77c7ce3
REPORT RequestId: f082a4ec-4bab-4463-b8c1-8fc2e77c7ce3  Init Duration: 0.15 ms  Duration: 242.61 ms     Billed Duration: 243 ms Memory Size: 128 MB     Max Memory Used: 128 MB
{"statusCode": 200, "body": "{\"message\": \"hello world\"}"}
```

2022-03-04 17:58 UTC, jfuss approved these changes

2022-03-07 17:53 UTC, mildaniel approved these changes

2022-03-07 17:54 UTC, merged