fix: Lock functions from building with same codeuri at the same time
aws/aws-sam-cli pull request #3862
Opened 2022-05-06 22:46 UTC by mildaniel

#### Which issue(s) does this change fix?

#3587

#### Why is this change necessary?
Resolves a race condition where functions with the same codeuri attempt to modify shared resources simultaneously during a build.

#### How does it address the issue?
Adds another lock to a function whenever functions share the same codeuri.

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [x] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [x] Write/update unit tests
- [x] Write/update integration tests
- [ ] Write/update functional tests if needed
- [x] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2022-05-06 23:02 UTC, mndeveci commented
I think we don't need following folders in the repository since they will be created once the function is built;
- `tests/integration/testdata/sync/code/after/dotnet_function/src/HelloWorld/bin/`
- `tests/integration/testdata/sync/code/before/dotnet_function/src/HelloWorld/bin/`

Rest looks good to me 👍🏼

2022-05-07 01:11 UTC, mndeveci requested changes

2022-05-07 01:11 UTC, mndeveci commented on tests/integration/testdata/sync/code/before/template-python.yaml
>          - Ref: HelloWorldLayer
This file name is no longer valid anymore (`template-python.yaml`). Let's move this function into its own template.

2022-05-07 01:11 UTC, mndeveci commented on tests/integration/testdata/sync/code/before/dotnet_function/src/HelloWorld/obj/HelloWorld.csproj.nuget.dgspec.json
> +{
Sorry if I missed this my earlier pass, but it looks like we also don't need this `obj` folder under function source. I believe this is generated during build so we don't need to push this in git.

2022-05-07 01:11 UTC, mndeveci commented on tests/integration/testdata/sync/code/after/dotnet_function/src/HelloWorld/obj/HelloWorld.csproj.nuget.dgspec.json
> +{
Same for this `obj` folder as well, we probably don't need this.

2022-05-10 19:32 UTC, mndeveci approved these changes
LGTM!

2022-05-12 00:03 UTC, qingchm approved these changes

2022-05-12 00:15 UTC, merged