feat: nested stack support for sam logs
aws/aws-sam-cli pull request #3881
Opened 2022-05-14 08:50 UTC by mndeveci

#### Which issue(s) does this change fix?

#### Why is this change necessary?

#### How does it address the issue?

#### What side effects does this change have?

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write/update unit tests
- [ ] Write/update integration tests
- [ ] Write/update functional tests if needed
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2022-05-17 22:58 UTC, mingkun2020 requested changes

2022-05-17 22:58 UTC, mingkun2020 commented on samcli/commands/logs/command.py
> +You can now fetch logs from supported resource, by only providing --stack-name parameter
nit: Should we use `resources` instead of `resource` here?

2022-05-17 22:58 UTC, mingkun2020 commented on samcli/commands/logs/logs_context.py
> +        for selected_resource_name in selected_resource_names:
It will iterate the tree for each selected_resource_name, use a dictionary (resources_id -> resource_summary) may improve the performance.

2022-05-18 00:12 UTC, mingkun2020 approved these changes
LGTM!

2022-05-20 01:32 UTC, qingchm approved these changes

2022-05-20 02:20 UTC, merged