README.md Updated typo fixes done.
aws/aws-sam-cli pull request #4032
Opened 2022-07-03 15:51 UTC by prasadjivane

Updated README.md typo fixes.

#### Which issue(s) does this change fix?

#### Why is this change necessary?

#### How does it address the issue?

#### What side effects does this change have?

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write/update unit tests
- [ ] Write/update integration tests
- [ ] Write/update functional tests if needed
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2022-07-03 18:51 UTC, hawflau requested changes
Thanks for your contribution. I left some questions in which I don't think those changes are necessary. Could your please review and update accordingly?

2022-07-03 18:51 UTC, hawflau commented on README.md
> +- **Compile, build, and package** Lambda functions with provided runtimes and with custom Makefile workflows, for zipping and image types of Lambda functions with `sam build`
not sure why you change it to a gerund. "zip" is a noun in this sentence (as in "zip type Lambda Function").

2022-07-03 18:51 UTC, hawflau commented on README.md
> +- **Locally test** a Lambda function and API Gateway quickly in a Docker container with `sam local` commands on SAM and CDK applications
"easily" makes sense to me. And this is not a typo. Why is changing to "quickly" more appropriate?

2022-07-03 18:51 UTC, hawflau commented on README.md
> +* [Detect when records added to a database](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-example-ddb.html) using Amazon DynamoDB database and asynchronous
I believe removing "are" is not grammatically correct.

2022-07-03 18:51 UTC, hawflau commented on README.md
> +It uses this excellent Python library called Click to manage the command line interaction and uses Docker to run Lambda functions locally.
this doesn't look like a typo to me. Why change it?

2022-07-03 18:51 UTC, hawflau commented on README.md
> +[SAM Developer Guide](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/index.html) provides a comprehensive getting started guide and reference documentation.
```suggestion
[SAM Developer Guide](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/index.html) provides a comprehensive getting started guide and a reference documentation.
```

2022-07-03 23:41 UTC, hawflau approved these changes

2022-07-08 18:36 UTC, mndeveci approved these changes

2022-07-08 18:36 UTC, merged