Add CodeQL GH Action
aws/aws-sam-cli pull request #4552
Opened 2023-01-09 19:10 UTC by hawflau

#### Which issue(s) does this change fix?

#### Why is this change necessary?
Enable Code Scan through GH Action

#### How does it address the issue?

#### What side effects does this change have?

#### Mandatory Checklist
**PRs will only be reviewed after checklist is complete**

- [ ] Add input/output [type hints](https://docs.python.org/3/library/typing.html) to new functions/methods
- [ ] Write design document if needed ([Do I need to write a design document?](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md#design-document))
- [ ] Write/update unit tests
- [ ] Write/update integration tests
- [ ] Write/update functional tests if needed
- [ ] `make pr` passes
- [ ] `make update-reproducible-reqs` if dependencies were changed
- [ ] Write documentation

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0).

2023-01-10 19:17 UTC, sriram-mv reviewed
Is this going to be a gating workflow, preventing PR merges? What kind of actions does the unsuccessful run of codeql action entail on us?

2023-01-10 19:17 UTC, sriram-mv commented on samcli/lib/pipeline/bootstrap/stage.py
> +        ctx.set_options(SSL.OP_NO_TLSv1)
should we verify this with unit tests?

2023-01-10 19:17 UTC, sriram-mv requested changes
Changing my review to reflect requesting changes.

2023-01-16 18:58 UTC, hawflau commented
@sriram-mv 

> Is this going to be a gating workflow, preventing PR merges? What kind of actions does the unsuccessful run of codeql action entail on us?

Yes, it's run on each PR. Failure of this action should prevent the PR from being merged. And the PR author should fix me. 

The action will also run on schedule, because existing code might be subjected to newly discovered vulnerabilities. We will get notified and also can check from the "Security" tab in the repo.

2023-01-16 19:58 UTC, hawflau commented on samcli/lib/pipeline/bootstrap/stage.py
> +        ctx.set_options(SSL.OP_NO_TLSv1)
Added

2023-01-16 21:34 UTC, torresxb1 approved these changes

2023-01-16 21:40 UTC, merged