fix: Fix the permission errors in Windows and add back the CVE-2007-4559 Patch changes
aws/aws-sam-cli pull request #4580
Opened 2023-01-16 21:18 UTC by hnnasit

Reverts aws/aws-sam-cli#4560

2023-01-18 18:37 UTC, hawflau requested changes

2023-01-18 18:37 UTC, hawflau commented on tests/functional/lib/utils/test_tar.py
> +class TestExtractTarFile(TestCase):
Can we also add a test to call `extract_tarfile` with the `file_obj` kw arg?

2023-01-19 18:36 UTC, hawflau approved these changes

2023-01-20 00:24 UTC, qingchm approved these changes
LGTM!

2023-01-20 03:38 UTC, merged